apiVersion: eksctl.io/v1alpha5
availabilityZones:
  - ap-southeast-1a
  - ap-southeast-1b
  - ap-southeast-1c
cloudWatch:
  clusterLogging: {}
iam:
  vpcResourceControllerPolicy: true
  withOIDC: false
kind: ClusterConfig
metadata:
  name: prod-ap-southeast-1-reviewty
  region: ap-southeast-1
  version: "1.20"
managedNodeGroups:
  - amiFamily: AmazonLinux2
    disableIMDSv1: false
    disablePodIMDS: false
    iam:
      withAddonPolicies:
        albIngress: false
        appMesh: false
        appMeshPreview: false
        autoScaler: true
        certManager: false
        cloudWatch: false
        ebs: false
        efs: false
        externalDNS: false
        fsx: false
        imageBuilder: false
        xRay: false
    instanceSelector: {}
    instanceType: m5.large
    labels:
      alpha.eksctl.io/cluster-name: prod-ap-southeast-1-reviewty
      alpha.eksctl.io/nodegroup-name: ng-api
    name: ng-api
    privateNetworking: false
    # securityGroups:
    #   withLocal: true
    #   withShared: true
    ssh:
      allow: true
      enableSsm: false
      publicKeyName: kubernetes_key
    volumeIOPS: 3000
    volumeSize: 50
    volumeThroughput: 125
    volumeType: gp3
privateCluster:
  enabled: false
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single
