# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# secretGenerator:
# - name: firebase-adminsdk
#   namespace: production
#   files:
#   - firebase-adminsdk.json
apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-key
  namespace: production
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIzMzkxMjYxNDY4NjEuZGtyLmVjci5hcC1zb3V0aGVhc3QtMS5hbWF6b25hd3MuY29tIjoge30sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHt9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIKfQ==
