# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# secretGenerator:
# - name: firebase-adminsdk
#   namespace: production
#   files:
#   - firebase-adminsdk.json
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-key
  namespace: production
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJhdXRoIjogImNtVjJhV1YzZEhrNlVtTTBlWHBqTUdrM04zSk0iCiAgICB9CiAgfQp9Cg==
